### ISSUE TITLE
Is there anyway to get team stats?

### ISSUE THREAD

**Issue by MichaelWS** [BurntSushi/nflgame#101]
Is there an example of an  approach for team stats?

I wanted to compute dst points using something like this.
http://games.espn.go.com/ffl/resources/help/content?name=scoring-settings-standard

**Comment by Greene48** [comment]
Thanks ochawkeye, I used code similar to this to calculate DST fantasy points.
Just an FYI for anyone else doing the same, for blocked kicks; this:

    team_defense_score[p.team] += p.kicking_fgb*2
    team_defense_score[p.team] += p.kicking_xpb*2
    team_defense_score[p.team] += p.punting_block*2

should actually be:

    team_defense_score[p.team] += p.defense_fgblk*2
    team_defense_score[p.team] += p.defense_xpblk*2
    team_defense_score[p.team] += p.defense_puntblk*2 

The stat types in the first few lines are for offensive players, so they only apply to the kickers themselves and get passed over since we are looking for defensive players only. Even if we didn't filter defensive players only, the points would be applied to the wrong team.
