### ISSUE TITLE
Voice.py error

### ISSUE THREAD

**Issue by pilotkid** [BurntSushi/nflgame#182]
Hello, I am attempting to send SMS messages through nflgame but I receive the following error.

**Error**

```
Traceback (most recent call last):
  File "C:\Users\Marcello\Desktop\ip_change_alert.py", line 4, in <module>
    nflgame.alert.google_voice_login("gmailemail@gmail.com","Password")
  File "C:\Python27\lib\site-packages\nflgame\alert.py", line 123, in google_voice_login
    _voice.login(email, passwd)
  File "build\bdist.win32\egg\googlevoice\voice.py", line 70, in login
AttributeError: 'NoneType' object has no attribute 'group'
```
I am using Windows 7 Enterprise with python 2.7.11.

**My code is:**
```
import nflgame.alert

nflgame.alert.google_voice_login("email@gmail.com","pass")
nflgame.alert.sms("pass","Test")
```

**I have tried the following:**
- Reinstalling the module
- Reinstalling all dependencies  
- Using different email accounts.

**Comment by BurntSushi** [comment]
It looks like a problem in the googlevoice package. Can't help you there, unfortunately. Honestly, I haven't used this part of nflgame in a few years, so I'm not surprised that it has rotted. I'll likely remove it in the future. Probably best to find another way. (Try sending SMS using email instead of Google Voice, but it will require knowing the service provider of the recipient.)

**Comment by ochawkeye** [comment]
I have not tried it, though a cursory search does uncover https://github.com/pettazz/pygooglevoice, a package that a) has been recently contributed to and b) appears to follow pretty closely to the original pygooglevoice API.
