### ISSUE TITLE
Stats not matching NFL.com?

### ISSUE THREAD

**Issue by jaunt7** [BurntSushi/nflgame#184]
Why would passing yards not match in NFL.com?
Example
Tom Brady Game 12, 2012 shows 295 yards, NFLshows 323
http://www.nfl.com/player/tombrady/2504211/gamelogs?season=2012

Is this a missing stat that isn't being mapped or is NFL changing their data?

**Comment by BurntSushi** [comment]
The GameCenter JSON (used in nflgame) isn't 100% accurate.

To actually see what's happening in your case, you'd need to look at the play-by-play and track down where the stats differ.

On occasion, stat inaccuracies are due to a bug in nflgame, but more frequently (especially if the yardage total is off by a few yards), it's because the source data is just wrong.

**Comment by jaunt7** [comment]
In this case I think the source JSON is missing the extra yards...by the way, thanks for all your hard work!  
To reconcile historical data, do you think it would be best for me to scrape the game stat summary NFL pages, and maybe scrape new game summaries days after games end? Or is there a better way, I'm thinking you've probably thought about this before...

**Comment by jaunt7** [comment]
I see you discuss stat corrections here, which I'm assuming happen with most discrepancies.
https://github.com/BurntSushi/nflgame/issues/63

I'll continue researching options.
