### ISSUE TITLE
Non-Skill Player Activity in Plays/Games

### ISSUE THREAD

**Issue by MTWebSer** [BurntSushi/nflgame#198]
Hi Andrew,

Big fan of the nfl data ecosystem you built, thanks for all the work put into this.

In an effort to quantify non-skill player performance, I was searching for a way to determine the active players at the play level. I.E. running back A has a 5 yard gain on the play, the active offensive line players are [X,Y,Z,...].

I assume that play level data isn't available for this sort of scenario or else it would be found in the json somewhere, but games played could be? 

In theory, one would be able to access data from a player's game log site like -
 http://www.nfl.com/player/jamescarpenter/2495134/gamelogs?season=2011 - to pull data related to Games Played (G column). This approach would at least allow for player composition detail around an offensive line's game level performance. I.E. Team 1's offensive line performance = X, Team 1's offensive line had participation from o-line players [Q,W,E,...], thus [Q,W,E,...]'s performance = X.

I was hoping that NFLGame might have a precedent for this - any thoughts on a solution/alternatives for this task?

Thanks
-Mike

**Comment by BurntSushi** [comment]
As a general rule, `nflgame` (and `nfldb`) don't scrape for data outside of the JSON feed. There are a few exceptions to this (such as current player meta data), but I generally don't want to head down that path. I'd rather see it built on top of nflgame or nfldb.

You are right of course that stats for "non skill" players are essentially non-existent.

**Comment by MTWebSer** [comment]
Thanks for the quick reply- completely agree with the avoidance of scraping and was hoping that I missed something in the JSON that could derive the value.

If you don't mind me asking, how did you stumble upon the Game Center json data? I am searching for more pro sports data sources and having a difficult time finding something similar for the NBA.

**Comment by BurntSushi** [comment]
I observed that the NFL GameCenter pages were updating asynchronously (i.e., without a full page refresh). This meant that updated stats were being pulled in periodically and sliced into the current page. It is much easier to do that when you receive structured data, so I just looked for XHR requests in the page using Chrome's developer tools (Firefox has something similar). I saw a JSON file, looked at the payload and started reverse engineering it.

nflgame and nfldb exist purely because of a quirk in the NFL GameCenter implementation. You'll need to look for similar quirks in other sports, but there's really no uniformity since they are entirely separate organizations. :-)

**Comment by ochawkeye** [comment]
> I am searching for more pro sports data sources and having a difficult time finding something similar for the NBA.

Have you had a look at [nba_py](https://github.com/seemethere/nba_py)?  The endpoints don't appear to be a concise single json file like NFL GameCenter uses, but it looks like they've cracked the code  a bit over there.
