### ISSUE TITLE
2016 data

### ISSUE THREAD

**Issue by jimkiely-brainiacdevs** [BurntSushi/nflgame#279]
'NoneType' object is not iterable

```
games = nflgame.games(2016)
for g in games:
    print('home:' + g.home + ', away:' + g.away + ', winner:' + g.winner)
```

**Comment by jimkiely-brainiacdevs** [comment]
Sorry duplicate issue.

**Comment by benschroeder** [comment]
I *think* this could be a legit problem for someone who just freshly installed `nflgame` via github after yesterday.

Since `nflgame`'s `gamecenter-json` does not include any games since September 1, someone that installed after #278 would not be picking up any that occurred during the regular season.

A merge like #278 should probably also include all of the new games in `gamecenter-json` that have happened to date.

If this is, in fact the case, you can work around this issue by changing `nflgame/live.py` [`_CUR_SCHEDULE`](https://github.com/jclapp23/nflgame/blob/33991da8a9e513dc1f167575519cb303839da2f2/nflgame/live.py#L68) temporarily back to the regular season URL, running your command (which will download all of the games to your `gamecenter-json` folder), then switching it back to the postseason URL.

**Comment by ochawkeye** [comment]
I think this could be a legit problem for someone who just freshly installed `nflgame` via github after yesterday.

Since `nflgame`'s `gamecenter-json` does not include any games since September 1, someone that installed after #278 would not be picking up any that occurred during the regular season.

A merge like #278 should probably also include all of the new games in gamecenter-json that have happened to date.

If this is, in fact the case, you can work around this issue by changing `nflgame/live.py` [`_CUR_SCHEDULE`](https://github.com/jclapp23/nflgame/blob/33991da8a9e513dc1f167575519cb303839da2f2/nflgame/live.py#L68) temporarily back to the regular season URL, running your command (which will download all of the games to your `gamecenter-json` folder), then switching it back to the postseason URL.
