### ISSUE TITLE
Missing player stats

### ISSUE THREAD

**Issue by andrewvandenheuvel** [BurntSushi/nflgame#286]
First, thanks for nflgame, I'm learning a lot and I'm really enjoying your work.
I noticed there are a few players whos stats are missing.

```
import nflgame
player = [ 'Antonio Brown','Malcolm Mitchell','Ty Montgomery','odell Beckham','doug baldwin']
games = nflgame.games(2016, kind="POST")
for p in player:
    print p
    player_name = nflgame.find(p)[0]
    for i, game in enumerate(games):
        if game.players.name(player_name.gsis_name):
            print "rec:",game.players.name(player_name.gsis_name).receiving_rec,
            print "yds:",game.players.name(player_name.gsis_name).receiving_yds,
            print "tds:",game.players.name(player_name.gsis_name).receiving_tds
```
returns: 

```
Antonio Brown
rec: 5 yds: 124 tds: 2
Malcolm Mitchell
Ty Montgomery
odell Beckham
doug baldwin
rec: 11 yds: 104 tds: 1
```

I noticed Ty Montgomery and Odell Beckham don't have any stats listed (Mitchell hasen't played yet). Is this an issue with the feed, or is there a way to fix this? This is the same for the regular season.
`player_name.__dict__ `shows the players url, and they link to the proper NFL.com page. Any Idea?

**Comment by ochawkeye** [comment]
This is a little bit complicated.  I think probably has to do with how and when `gsis_names` get added into the metadata stored by `nflgame`.  

The cases where stats are "missing" are for related reasons.  Will take Odell Beckham as an example but similar problems will hold true for the others.

When the NFL added him, they were using `gsis_name` of "O.Beckham Jr.".  This appears in the file `players.json`:
```
    "00-0031235": {
        "birthdate": "11/5/1992",
        "college": "LSU",
        "first_name": "Odell",
        "full_name": "Odell Beckham",
        "gsis_id": "00-0031235",
        "gsis_name": "O.Beckham Jr.",
        "height": 71,
        "last_name": "Beckham",
        "number": 13,
        "position": "WR",
        "profile_id": 2543496,
        "profile_url": "http://www.nfl.com/player/odellbeckham/2543496/profile",
        "status": "ACT",
        "team": "NYG",
        "weight": 198,
        "years_pro": 3
    },
```
and can be accessed in `nflgame`:
```python
import nflgame
player = nflgame.find('Odell Beckham')[0]
print player, player.gsis_name
```
```
Odell Beckham (WR, NYG) O.Beckham Jr.
```


Unfortunately, at some point, the NFL decided to just start calling him "O.Beckham".  That's who appeared in the game last week. (see the 31st person in this list:)
```python
import nflgame
games = nflgame.games_gen(2016, kind='POST', home='GB', away='NYG')
for game in games:
    print game.players
```
```
[A.Rodgers, C.Michael, T.Montgomery, A.Ripkowski, J.Nelson, G.Allison, J.Cook, D.Adams, R.Cobb, C.Matthews, M.Crosby, J.Schum, J.Janis, M.Hyde, B.Martinez, L.Gunter, J.Ryan, D.Jones, M.Burnett, D.Randall, J.Thomas, L.Guion, K.Brice, H.Clinton-Dix, J.Peppers, M.Daniels, E.Manning, P.Perkins, R.Jennings, B.Rainey, O.Beckham, W.Tye, T.King, V.Cruz, S.Shepard, R.Gould, B.Wing, D.Harris, T.Wade, D.Kennard, D.Harrison, O.Vernon, L.Collins, R.Thomas, C.Sensabaugh, J.Hankins, K.Robinson, J.Casillas, J.Jenkins, R.Okwara, J.Bromley, L.Hall, K.Wynn, E.Apple]
```

In an effort to not be rude to NFL.com, those thousands of players that are in `nflgame` aren't updated once they're in the system.  They're kind of frozen.  So, if the NFL changes what short name they call them, then `nflgame` doesn't ever know.  In the case of Beckham, his short name has changed multiple times back and forth throughout the years.  In a similar vein, when the NFL added Malcolm Mitchell & Ty Montgomery to their rosters, they didn't even assign them an `gsis_id`.  (See players "00-0032400" and "00-0032200" in the previously mentioned `players.json` file).

But even without those issues, in truth `gsis_name` isn't a very good "name" to use since it may or may not be unique to the player (think about, for example, Charles Johnson vs. Calvin Johnson vs. Chris Johnson gsis_name).  A much better - and most importantly, unique - reference is the `player_id`.

I won't change your code too much (though it's pretty redundant to loop over every single game for every single player)...

```
import nflgame
player = [ 'Antonio Brown','Malcolm Mitchell','Ty Montgomery','odell Beckham','doug baldwin']
games = nflgame.games(2016, kind="POST")
for p in player:
    print p

    player = nflgame.find(p)[0]

    for i, game in enumerate(games):
        game_player_ids = [p.playerid for p in game.players]
        if player.player_id in game_player_ids:
            game_player = game.players.playerid(player.player_id)
            print "rec:", game_player.receiving_rec,
            print "yds:", game_player.receiving_yds,
            print "tds:", game_player.receiving_tds
    print '-'*25
```

```
Antonio Brown
rec: 5 yds: 124 tds: 2
-------------------------
Malcolm Mitchell
-------------------------
Ty Montgomery
rec: 3 yds: 41 tds: 0
-------------------------
odell Beckham
rec: 4 yds: 28 tds: 0
-------------------------
doug baldwin
rec: 11 yds: 104 tds: 1
-------------------------
[Finished in 1.4s]
```

(I'll save the `nflgame` vs. `nfldb` fuzzy name matching conversation for another day.)

**Comment by andrewvandenheuvel** [comment]
Thank you for your quick response and explanation. This resolved my issue. Looks like player_id is more accurate and more reliable.
